/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface.Admin;

import java.awt.geom.RoundRectangle2D;
import java.text.SimpleDateFormat;
import java.sql.*;
import MySQLConnection.ConnectionProvider;
import CalculateDay.CalculateDayAfter;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import javax.swing.JOptionPane;
import CheckValidation.CheckValidPhoneNumber;
import CalculateDay.CalculateDayBetween;

/**
 *
 * @author Phạm Việt Hoàng
 */
public class AdminUpdateDonor extends javax.swing.JFrame {

    private static String storedLastDonationDate = null;

    /**
     * Creates new form AdminUpdateDonor
     */
    public AdminUpdateDonor() {
        initComponents();
        this.setLocationRelativeTo(null);
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 20, 20));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jComboBox1 = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("UPDATE DONOR INFO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 21, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 87, 748, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("DonorID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 118, -1, -1));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 115, 75, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/search.png"))); // NOI18N
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 115, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 160, 748, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Fullname");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 191, -1, -1));

        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 188, 200, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Gender");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 241, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Date of birth");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 291, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Social Security Number");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 341, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Phone number");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 391, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("City");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 441, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("District");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 491, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Street");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 541, -1, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 585, 748, 10));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 238, 200, -1));

        jDateChooser1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jDateChooser1.setDateFormatString("dd-MM-yyyy");
        jDateChooser1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 288, 200, -1));

        jTextField3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 338, 200, -1));

        jTextField4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 388, 200, -1));

        jTextField5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 438, 200, -1));

        jTextField6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 488, 200, -1));

        jTextField7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 538, 200, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Blood group");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 191, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Donated times");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 241, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Last donation date");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 291, -1, -1));

        jTextField9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 238, 200, -1));

        jDateChooser2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jDateChooser2.setDateFormatString("dd-MM-yyyy");
        jDateChooser2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 288, 200, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 102, 102));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/save.png"))); // NOI18N
        jButton2.setText("SAVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 620, -1, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 102, 102));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/reset.png"))); // NOI18N
        jButton3.setText("RESET");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 620, -1, -1));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 102, 102));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/cancel.png"))); // NOI18N
        jButton4.setText("CANCEL");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 620, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("(Blood Volume)");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 341, -1, -1));

        jTextField10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 338, 200, -1));

        jComboBox2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "O+", "O-", "A+", "A-", "B+", "B- ", "AB+", "AB-" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 188, 200, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/Background.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        jTextField3.setEditable(false);
        jTextField9.setEditable(false);
        jComboBox1.getModel().setSelectedItem(null);
        jComboBox2.getModel().setSelectedItem(null);
    }//GEN-LAST:event_formComponentShown

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String donorID = jTextField1.getText();
        try {
            Connection con = ConnectionProvider.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from donor where DonorID = '" + donorID + "'");
            if (rs.next()) {
                jTextField2.setText(rs.getString("Fullname"));
                jComboBox1.getModel().setSelectedItem(rs.getString("Gender"));
                jDateChooser1.setDate(new SimpleDateFormat("dd-MM-yyyy").parse(rs.getString("DateOfBirth")));
                jTextField3.setText(rs.getString("SSN"));
                jTextField4.setText(rs.getString("PhoneNumber"));
                jTextField5.setText(rs.getString("City"));
                jTextField6.setText(rs.getString("District"));
                jTextField7.setText(rs.getString("Street"));
                jComboBox2.getModel().setSelectedItem(rs.getString("BloodGroup"));
                if (jComboBox2.getModel().getSelectedItem() != null) {
                    jComboBox2.setEnabled(false);
                } else {
                    jComboBox2.setEnabled(true);
                }
                jTextField9.setText(rs.getString("DonatedTimes"));
                if (rs.getString("LastDonationDate") == null) {
                    jDateChooser2.setDate(new SimpleDateFormat("dd-MM-yyyy").parse("01-01-1"));
                } else {
                    jDateChooser2.setDate(new SimpleDateFormat("dd-MM-yyyy").parse(rs.getString("LastDonationDate")));
                }
                if (jDateChooser2.getDate() == null) {
                    storedLastDonationDate = "00-00-0000";
                } else {
                    SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
                    storedLastDonationDate = dateFormat.format(jDateChooser2.getDate());
                }
            } else {
                JOptionPane.showMessageDialog(null, "Donor ID does not exist");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (CalculateDayBetween.CalculateDayBetween(new SimpleDateFormat("dd-MM-yyyy").format(jDateChooser2.getDate())) > 0) {
            System.out.println("No");
        }
        if (jTextField2.getText().isBlank() || jTextField4.getText().isBlank()
                || jTextField5.getText().isBlank() || jTextField6.getText().isBlank()
                || jTextField7.getText().isBlank()
                || jDateChooser1.getDate() == null
                || jDateChooser2.getDate() == null
                || jComboBox1.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "All fields must be filled");
        } else {
            if (!CheckValidPhoneNumber.checkValidPhoneNumber(jTextField4.getText())) {
                JOptionPane.showMessageDialog(null, "Phone number is invalid");
            } else {
                try {
                    if (storedLastDonationDate.equals(new SimpleDateFormat("dd-MM-yyyy").format(jDateChooser2.getDate()))) {
                        String donorID = jTextField1.getText();
                        String fullName = jTextField2.getText();
                        String gender = (String) jComboBox1.getSelectedItem();
                        String phoneNumber = jTextField4.getText();
                        String city = jTextField5.getText();
                        String district = jTextField6.getText();
                        String street = jTextField7.getText();

                        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
                        String dateOfBirth = dateFormat.format(jDateChooser1.getDate());
                        try {
                            Connection con = ConnectionProvider.getConnection();
                            Statement st = con.createStatement();
                            st.executeUpdate("update donor set FullName = '" + fullName + "', Gender = '" + gender + "', DateOfBirth = '" + dateOfBirth + "', PhoneNumber = '" + phoneNumber + "', City = '" + city + "', District = '" + district + "', Street = '" + street + "' where DonorID = '" + donorID + "'");
                            JOptionPane.showMessageDialog(null, "Updated successfully");
                            setVisible(false);
                            new AdminUpdateDonor().setVisible(true);
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, e);
                        }
                    } else {
                        if (jComboBox2.getModel().getSelectedItem() == null || jTextField10.getText().isBlank()
                                || jDateChooser2.getDate() == null) {
                            JOptionPane.showMessageDialog(null, "All fields must be filled");
                        } else {
                            if ((new SimpleDateFormat("dd-MM-yyyy").parse(storedLastDonationDate)).after(jDateChooser2.getDate())
                                    || CalculateDayBetween.CalculateDayBetween(new SimpleDateFormat("dd-MM-yyyy").format(jDateChooser2.getDate())) > 0) {
                                JOptionPane.showMessageDialog(null, "Last donation date is invalid");
                            } else {
                                String donorID = jTextField1.getText();
                                String fullName = jTextField2.getText();
                                String gender = (String) jComboBox1.getSelectedItem();
                                String ssn = jTextField3.getText();
                                String email = null;
                                try {
                                    Connection con = ConnectionProvider.getConnection();
                                    Statement st = con.createStatement();
                                    ResultSet rs = st.executeQuery("select * from donor where DonorID = '" + donorID + "' and SSN = '" + ssn + "'");
                                    if (rs.next()) {
                                        email = rs.getString("Email");
                                    }
                                } catch (Exception e) {
                                    JOptionPane.showMessageDialog(null, e);
                                }
                                String phoneNumber = jTextField4.getText();
                                String city = jTextField5.getText();
                                String district = jTextField6.getText();
                                String street = jTextField7.getText();
                                String bloodGroup = (String) jComboBox2.getSelectedItem();
                                int donatedTimes = 1;
                                if (!jTextField9.getText().isBlank()) {
                                    donatedTimes = Integer.parseInt(jTextField9.getText()) + 1;
                                }
                                String bloodVolume = jTextField10.getText() + " ml";

                                SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
                                String dateOfBirth = dateFormat.format(jDateChooser1.getDate());
                                String lastDonationDate = dateFormat.format(jDateChooser2.getDate());
                                String nextDonationDate = CalculateDayAfter.calculateDayAfter(lastDonationDate);

                                try {
                                    Connection con = ConnectionProvider.getConnection();
                                    Statement st = con.createStatement();
                                    st.executeUpdate("update donor set FullName = '" + fullName + "', Gender = '" + gender + "', DateOfBirth = '" + dateOfBirth + "', PhoneNumber = '" + phoneNumber + "', City = '" + city + "', District = '" + district + "', Street = '" + street + "', "
                                            + "BloodGroup = '" + bloodGroup + "', DonatedTimes = '" + String.valueOf(donatedTimes) + "', LastDonationDate = '" + lastDonationDate + "', NextDonationDate = '" + nextDonationDate + "'   where DonorID = '" + donorID + "'");
                                    st.executeUpdate("insert into history value('" + donorID + "', '" + lastDonationDate + "', '" + bloodVolume + "')");
                                    JOptionPane.showMessageDialog(null, "Updated successfully");
                                    setVisible(false);
                                    new AdminUpdateDonor().setVisible(true);
                                } catch (Exception e) {
                                    JOptionPane.showMessageDialog(null, e);
                                }
                            }
                        }
                    }
                } catch (ParseException ex) {
                    java.util.logging.Logger.getLogger(AdminUpdateDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new AdminUpdateDonor().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String donorID = jTextField1.getText();
            try {
                Connection con = ConnectionProvider.getConnection();
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("select * from donor where DonorID = '" + donorID + "'");
                if (rs.next()) {
                    jTextField2.setText(rs.getString("Fullname"));
                    jComboBox1.getModel().setSelectedItem(rs.getString("Gender"));
                    jDateChooser1.setDate(new SimpleDateFormat("dd-MM-yyyy").parse(rs.getString("DateOfBirth")));
                    jTextField3.setText(rs.getString("SSN"));
                    jTextField4.setText(rs.getString("PhoneNumber"));
                    jTextField5.setText(rs.getString("City"));
                    jTextField6.setText(rs.getString("District"));
                    jTextField7.setText(rs.getString("Street"));
                    jComboBox2.getModel().setSelectedItem(rs.getString("BloodGroup"));
                    if (jComboBox2.getModel().getSelectedItem() != null) {
                        jComboBox2.setEnabled(false);
                    } else {
                        jComboBox2.setEnabled(true);
                    }
                    jTextField9.setText(rs.getString("DonatedTimes"));
                    if (rs.getString("LastDonationDate") == null) {
                        jDateChooser2.setDate(new SimpleDateFormat("dd-MM-yyyy").parse("01-01-1"));
                    } else {
                        jDateChooser2.setDate(new SimpleDateFormat("dd-MM-yyyy").parse(rs.getString("LastDonationDate")));
                    }
                    if (jDateChooser2.getDate() == null) {
                        storedLastDonationDate = "00-00-0000";
                    } else {
                        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
                        storedLastDonationDate = dateFormat.format(jDateChooser2.getDate());
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Donor ID does not exist");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUpdateDonor.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUpdateDonor.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUpdateDonor.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUpdateDonor.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUpdateDonor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
